# Generated by Django 3.2.4 on 2021-06-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210611_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'ordering': ['title'], 'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d', verbose_name='Фото категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.categoryproduct', verbose_name='Категория продуктов'),
        ),
    ]
